name: Run API tests

on:
  push:
    branches:
      - main
      - github-actions-integration
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -R

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies for Api.Tests
        run: dotnet restore ./Api.Tests/Api.Tests.csproj

      - name: Build project Api.Tests
        run: dotnet build ./Api.Tests/Api.Tests.csproj --no-restore

      - name: Run tests for Api.Tests
        working-directory: ./Api.Tests
        run: dotnet test Api.Tests.csproj --no-build --verbosity normal
